# Generated by Django 4.0rc1 on 2025-01-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hold',
            field=models.ManyToManyField(related_name='holded_users', to='main.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=150, verbose_name='内容'),
        ),
    ]
