# Generated by Django 4.0rc1 on 2025-01-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_hold_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hold',
            field=models.ManyToManyField(blank=True, related_name='holded_users', to='main.Post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to='main.Post'),
        ),
    ]
