# Generated by Django 4.0rc1 on 2025-01-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_hold_alter_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='匿名投稿'),
        ),
    ]
